vars:
  - docs: &docs "/home/user/Documents"
  - pics: &base_pics "/home/user/Pictures"
  - dl: &deep_learning "/home/user/Documents/Bibliography/CS/Machine Learning & Data Science/Deep Learning"
  
  
pdf:
  new_folder: *docs
  patterns:
    - regex: ".*deep learning.*"
      new_folder: *deep_learning
    - regex: ".*neural.*"
      new_folder: *deep_learning

docx:
  new_folder: *docs

jpg:
  new_folder: *base_pics
  patterns:
    - regex: ".*unsplash.*"
      new_folder: "/home/cabero/Pictures/Wallpapers"

jpeg:
  new_folder: *base_pics

py:
  new_folder: "/home/cabero/Code/Python"

rs:
  new_folder: "/home/cabero/Code/Rust"

ts:
  new_folder: "/home/cabero/Code/Web-Development"

go:
  new_folder: "/home/cabero/Code/Go/src/"

sh:
  new_folder: "/home/cabero/Code/Bash"
